import resnet_v1_101_deeplab
import resnet_v1_101_deeplab_dcn
import resnet_v1_101_deeplab_video
import resnet_v1_101_deeplab_video_dcn
# Capsule Layer For Segmentation
# import resnet_v1_101_deeplab_capsule
# import densenet_bc_deeplab_base
# import densenet_bc_deeplab_base_v2